Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -12,6 +12,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+          persist-credentials: false
 
       - name: Push to Mirror Repo with CNAME
         env:
@@ -19,16 +20,15 @@ jobs:
         run: |
           set -e
           if [ -z "$GH_PAT" ]; then
-            echo "::error::GH_PAT is empty. Check repository secrets."
+            echo "::error::GH_PAT is empty"
             exit 1
           fi
 
           echo "smartlegionlab.com" > CNAME
-
           git config user.name  "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
           git add -f CNAME
-          git commit -m "chore: add CNAME for custom domain" || echo "CNAME unchanged, skipping commit"
+          git commit -m "chore: add CNAME" || true
 
           git remote add mirror "https://github.com/smartlegionlab/smartlegionlab-com.git"
           git -c http.extraHeader="AUTHORIZATION: bearer ${GH_PAT}" push mirror master:master --force
